### ISSUE TITLE
[DOCS] 프론트엔드 폴더 구조 정의

### ISSUE THREAD

**Issue by cruelladevil** [woowacourse-teams/2023-shook#119]
## 🤷 개선할 기능

프론트엔드 폴더 구조를 정의 내린다.

## 🔨 상세 작업 내용

- [ ] 프론트엔드 폴더 구조를 정의 내린다.

## 📄 참고 사항

폴더 구조에 대한 여러 관점을 파악한 후, **우리 프로젝트에 맞는 폴더 구조**를 정의한다.
🚨 완벽한 구조는 없습니다. **취할 장점과 감수할 단점**을 고려하세요.

https://ahnheejong.name/articles/package-structure-with-the-principal-of-locality-in-mind/
https://medium.com/sahibinden-technology/package-by-layer-vs-package-by-feature-7e89cde2ae3a

## ⏰ 예상 작업 시간

1시간

## ⏰ 마감일

7/27

**Comment by Creative-Lee** [comment]
회의 잘 마무리 되었습니다 종료합니다!
