### ISSUE TITLE
[BUG] 투표하기에서 화면 focus를 해제했다 다시 focus를 하면 재생시간이 초기화 되는 현상

### ISSUE THREAD

**Issue by 2yunseong** [woowacourse-teams/2023-shook#207]
## 버그 기능
- 투표하기에서 화면 focus를 해제했다 다시 focus를 하면 기록이 초기화 되는 현상이 있습니다.

## 버그 상황 재연
1. 투표하기에서 유튜브 재생 (https://s-hook.com/4)
2. 일시정지
3. 다른 화면에 포커스 (브라우저 외)
4. 다시 포커스 하면 유튜브 재생시간이 초기화 됨

## 기대 동작
- 재생시간이 그대로 유지됨

**Comment by Creative-Lee** [comment]
08 19 기준 해결되었습니다!
