### ISSUE TITLE
[BUG] 더보기 버튼을 누르면 유튜브 페이지로 이동하는 문제

### ISSUE THREAD

**Issue by kangyeongmin** [woowacourse-teams/2023-shook#210]
## 버그 기능

<img width="1055" alt="스크린샷 2023-08-07 오후 1 59 45" src="https://github.com/woowacourse-teams/2023-shook/assets/62367797/a5724ebf-cc9b-4b9b-8e9c-42f3a0aa1c03">

## 버그 상황 재연

: 페이스북, 트위터, 옆에 있는 더보기 버튼을 누르면 유튜브 페이지로 이동하는 플로우가 어색한 것 같습니다. 

## 기대 동작

: 또 다른 공유 방법들에 대한 정보가 보여질거라 기대했어요. 더보기 버튼보다 차라리 유튜브 아이콘으로 보여지게 하는것이 어떨까요?

**Comment by cruelladevil** [comment]
해당 부분은 youtube iframe 내부 구현, 즉 유튜브에서 만든 인터페이스입니다.
아쉽게도 변경이 불가능해요 😭
