### ISSUE TITLE
[BUG] 공백의 댓글을 등록하면 토스트 UI와 다르게 동작하는 현상

### ISSUE THREAD

**Issue by 2yunseong** [woowacourse-teams/2023-shook#211]
## 버그 기능
- 공백의 댓글을 제출하면 토스트 UI는 댓글이 등록되었다고 알람이 뜨는데 실제로는 댓글이 등록되지 않는 현상이 있습니다!! 

## 버그 상황 재연
- https://s-hook.com/song/6에 접속
- 킬링파트 1st 클릭
- 댓글 달기에 공백 입력 후 엔터
- 댓글이 등록되었습니다 토스트 메세지 등장
- 새로고침하면 댓글이 나오지 않음

## 기대 동작
- 공백만 입력된 댓글을 제한하거나 공백만 입력된 댓글이 등록됨

**Comment by cruelladevil** [comment]
연관이슈 #208
