### ISSUE TITLE
[BUG] 처음 댓글을 달면 1일 후로 나왔다가 0일 전으로 나오는 현상

### ISSUE THREAD

**Issue by 70825** [woowacourse-teams/2023-shook#213]
## 버그 기능
- 댓글을 등록하면 처음에 1일 후로 잠깐 나왔다가 다시 0일 전으로 되돌아옵니다.

## 버그 상황 재연
댓글 등록하고 바로 캡처
<img width="1151" alt="스크린샷 2023-08-07 오후 2 08 32" src="https://github.com/woowacourse-teams/2023-shook/assets/79046106/b6c72674-d6d0-4cbd-a345-59817d11cc38">

## 기대 동작
- 댓글 등록을 하면 바로 0일 전으로 나와야 할 것 같습니다.

**Comment by eunkeeee** [comment]
![image](https://github.com/woowacourse-teams/2023-shook/assets/107979804/0c48faf7-b1e3-4069-a46d-186899aaf985)

저는 처음부터 0일 전으로 나옵니다
