### ISSUE TITLE
[REFACTOR] Album 자켓 이미지 Thumbnail 컴포넌트 사용하여 적용

### ISSUE THREAD

**Issue by ukkodeveloper** [woowacourse-teams/2023-shook#442]
## 🤷 개선할 기능
Album 자켓 이미지 Thumbnail 컴포넌트 사용하여 적용
## 🔨 상세 작업 내용
- [ ] 이미 구현된 Thumbnail 컴포넌트를 재사용한다.

## ⏰ 예상 작업 시간
10분

## ⏰ 마감일
9.24

**Comment by Creative-Lee** [comment]
thumbnail 컴포넌트에 size prop으로 lg가 추가되었으니, 적용하면 되겠네요~ ㅎㅎ
