### ISSUE TITLE
[REFACTOR] 스타일드 컴포넌트 $붙여주어 dom 에러 메세지 나지 않도록 개선하기

### ISSUE THREAD

**Issue by ukkodeveloper** [woowacourse-teams/2023-shook#443]
## 🤷 개선할 기능
스타일드 컴포넌트 $붙여주어 dom 에러 메세지 나지 않도록 개선하기
## 🔨 상세 작업 내용
- [x] 캐러셀 컴포넌트 수정하기
- [ ] 추가 수정할 컴포넌트 없는 지 확인하기

## ⏰ 예상 작업 시간
10분

## ⏰ 마감일
9.24(일)

**Comment by Creative-Lee** [comment]
종료된 PR, 이슈 닫습니당
