### ISSUE TITLE
[FEAT] PR에 자동으로 리뷰어를 설정하는 기능을 추가한다.

### ISSUE THREAD

**Issue by Cyma-s** [woowacourse-teams/2023-shook#54]
## 🤷 구현할 기능
PR에 자동으로 리뷰어를 설정하는 기능을 추가한다.

## 📄 참고 사항
/frontend/ 하위 파일의 경우, @Creative-Lee , @ukkodeveloper , @cruelladevil 를 리뷰어로 설정한다.
/backend/ 하위 파일의 경우, @Cyma-s , @splitCoding , @somsom13 , @seokhwan-an 을 리뷰어로 설정한다.

## ⏰ 예상 작업 시간
30분

## ⏰ 마감일
필수적인 피쳐는 아니므로 레벨 3 ~ 4 내 언제든지

**Comment by Creative-Lee** [comment]
이게 된다구요? ㄷㄷ
