### ISSUE TITLE
[FEAT] 글로벌 스타일을 정의한다

### ISSUE THREAD

**Issue by cruelladevil** [woowacourse-teams/2023-shook#82]
## 🤷 구현할 기능

글로벌 스타일 및 theme을 적용한다.

## 🔨 상세 작업 내용

- [x] GlobalStyle
- [x] theme

## ⏰ 예상 작업 시간

2시간

## ⏰ 마감일

7월 18일

**Comment by Creative-Lee** [comment]
완료한 이슈 close 합니다~
